name: ci

on: [push, pull_request, workflow_call]

jobs:

  tests:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ["3.9", "3.10", "3.11"]
        aiida-version: ["aiida-core>=2.6"]
        pandas-version: ["pandas==1.5", "pandas>=2.3"]
        include:
            - python-version: "3.8"
              aiida-version: "aiida-core==1.6.9"
              pandas-version: "pandas==1.3"
              allowed-to-fail: false
            - python-version: "3.8"
              aiida-version: "aiida-core>=2.6"
              pandas-version: "pandas==1.5"
              allowed-to-fail: false
            - python-version: "3.12"
              aiida-version: "aiida-core>=2.6"
              pandas-version: "pandas>=2.3"
              allowed-to-fail: false
            - python-version: "3.13"
              aiida-version: "aiida-core>=2.6"
              pandas-version: "pandas>=2.3"
              allowed-to-fail: false
      fail-fast: False

    services:
      postgres:
        image: postgres:10
        env:
          POSTGRES_DB: test_aiida
          POSTGRES_PASSWORD: ''
          POSTGRES_HOST_AUTH_METHOD: trust
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      rabbitmq:
        image: rabbitmq:latest
        ports:
          - 5672:5672

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[testing]
        pip install ${{ matrix.aiida-version }} ${{ matrix.pandas-version }}
        reentry scan || true

    - name: Run test suite
      env:
        # show timings of tests
        PYTEST_ADDOPTS: "--durations=0"
      run: pytest --cov aiida_dataframe --cov-report=xml --cov-append .

    - name: Upload code coverage report
      run: |
        pip install codecov
        codecov


  docs:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[docs]
    - name: Build docs
      run: cd docs && make

  pre-commit:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install python dependencies
      run: |
        pip install --upgrade pip
        pip install -e .[pre-commit,docs,testing]
    - name: Run pre-commit
      run: |
        pre-commit install
        pre-commit run --all-files || ( git status --short ; git diff ; exit 1 )
